"""add document_id to sessions

Revision ID: 1027cc92fa28
Revises: 5568cdd72045
Create Date: 2026-05-18 13:36:45.999396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1027cc92fa28'
down_revision: Union[str, Sequence[str], None] = '5568cdd72045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'document_id')
    # ### end Alembic commands ###
